# Generated by Django 5.0.3 on 2024-04-11 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_rename_history_historyitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='release_date_precision',
            field=models.CharField(default='year', max_length=10),
            preserve_default=False,
        ),
    ]
