# Generated by Django 5.0.3 on 2024-04-06 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0002_oauthstate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauthstate',
            name='state',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='spotifytoken',
            name='access_token',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='spotifytoken',
            name='refresh_token',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='spotifytoken',
            name='token_type',
            field=models.CharField(max_length=250),
        ),
    ]
